In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/Social_Network_Ads.csv',
                 usecols=['Age','EstimatedSalary','Purchased'])

In [ ]:
df.head()

Age  EstimatedSalary  Purchased
0   19            19000          0
1   35            20000          0
2   26            43000          0
3   27            57000          0
4   19            76000          0

In [ ]:
x=df.drop(columns=['Purchased'])
y=df['Purchased']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,
                                                       random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc=StandardScaler()

In [ ]:
x_train_new = sc.fit_transform(x_train)

In [ ]:
x_test_new = sc.transform(x_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB , MultinomialNB , BernoulliNB

In [ ]:
classifier = GaussianNB()

In [ ]:
classifier.fit(x_train_new , y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(x_test_new)

In [ ]:
y_pred

array([1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       1, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0])

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
cn = confusion_matrix(y_test,y_pred)
cn

array([[50,  2],
       [ 3, 25]])

In [ ]:
# [[tp,fn]]
# [[fp,tn]]

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test , y_pred)

0.9375

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
precision_score(y_test,y_pred)

0.9259259259259259

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
recall_score(y_test , y_pred)

0.8928571428571429

In [ ]:
from sklearn.metrics import f1_score

In [ ]:
f1_score(y_test , y_pred)

0.9090909090909091

In [ ]:
df = pd.read_csv('/content/covid_toy.csv')
df.head()

age  gender  fever cough     city has_covid
0   60    Male  103.0  Mild  Kolkata        No
1   27    Male  100.0  Mild    Delhi       Yes
2   42    Male  101.0  Mild    Delhi        No
3   31  Female   98.0  Mild  Kolkata        No
4   65  Female  101.0  Mild   Mumbai        No

In [ ]:
df.isnull().sum()

age           0
gender        0
fever        10
cough         0
city          0
has_covid     0
dtype: int64

In [ ]:
from sklearn.impute import SimpleImputer

In [ ]:
si = SimpleImputer()

In [ ]:
df['fever']= si.fit_transform(df[['fever']])

In [ ]:
df.isnull().sum()

age          0
gender       0
fever        0
cough        0
city         0
has_covid    0
dtype: int64

In [ ]:
from sklearn.preprocessing import LabelEncoder

In [ ]:
lb = LabelEncoder()

In [ ]:
df['gender']=lb.fit_transform(df['gender'])
df['cough']=lb.fit_transform(df['cough'])
df['city']=lb.fit_transform(df['city'])
df['has_covid']=lb.fit_transform(df['has_covid'])

In [ ]:
x = df.drop(columns=['has_covid'])
y = df['has_covid']

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2,
                                                       random_state=42)

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
sc = StandardScaler()

In [ ]:
x_train_new = sc.fit_transform(x_train)

In [ ]:
x_test_new = sc.transform(x_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB , MultinomialNB , BernoulliNB

In [ ]:
classifier = GaussianNB()

In [ ]:
classifier.fit(x_train_new , y_train)

GaussianNB()

In [ ]:
y_pred = classifier.predict(x_test_new)

In [ ]:
from sklearn.metrics import confusion_matrix

In [ ]:
confusion_matrix(y_test , y_pred)

array([[8, 5],
       [3, 4]])

In [ ]:
from sklearn.metrics import accuracy_score

In [ ]:
accuracy_score(y_test , y_pred)

0.6

In [ ]:
from sklearn.metrics import precision_score

In [ ]:
precision_score(y_test , y_pred)

0.4444444444444444

In [ ]:
from sklearn.metrics import recall_score

In [ ]:
recall_score(y_test , y_pred)

0.5714285714285714

In [ ]:
from sklearn.metrics import f1_score

In [ ]:
f1_score(y_test , y_pred)

0.5